name: pipeline-trigger

on:
  push:
    branches:
    - dev
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://54.243.101.47:8080/"
        user: "ajin"
        token: ${{ secrets.TOKEN }}
        job: "dev"
